name: Continuous Deployment (Laravel)

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Continuous Testing (Laravel)"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, mysql

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Copy .env
      run: cp .env.example .env
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Generate app key
      run: php artisan key:generate
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Deploy to Server via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /var/www/aplikasi-workersunion
          git pull origin main
          composer install --no-progress --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan queue:restart
        EOF
