name: Continuous Testing (Laravel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, mysql
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Copy .env
      run: cp .env.example .env
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Generate app key
      run: php artisan key:generate
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Run Laravel tests with coverage
      run: php artisan test --coverage
      working-directory: APLIKASI/Aplikasi-WorkersUnion

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: APLIKASI/Aplikasi-WorkersUnion/tests/coverage
